// src/components/xray/CategoryFilter.vue
<!--
  Category Filter Component
  Allows users to filter treemap by content type categories
-->
<template>
  <div>
    <div class="flex items-center justify-between mb-3">
      <h3 class="text-sm font-medium text-gray-900">Filter by Content Type</h3>
      <button
        @click="handleToggleAll"
        class="text-sm text-blue-600 hover:text-blue-800 font-medium"
      >
        {{ allSelected ? 'Clear All' : 'Select All' }}
      </button>
    </div>

    <div class="flex flex-wrap gap-2">
      <button
        v-for="entry in typeLegend"
        :key="entry.type"
        @click="toggleCategory(entry.type)"
        :class="[
          'inline-flex items-center gap-2 px-3 py-1.5 rounded-md text-sm font-medium transition-all',
          isActive(entry.type)
            ? 'bg-white border-2 border-gray-300 text-gray-900'
            : 'bg-gray-100 border-2 border-transparent text-gray-400'
        ]"
      >
        <span
          class="w-3 h-3 rounded-sm"
          :style="{ backgroundColor: entry.color }"
        />
        <span>{{ entry.label }}</span>
      </button>
    </div>

    <div
      v-if="selectedCategories.size > 0 && selectedCategories.size < typeLegend.length"
      class="mt-3 text-sm text-gray-600"
    >
      Showing {{ selectedCategories.size }} of {{ typeLegend.length }} categories
    </div>
  </div>
</template>

<script>
import { computed } from 'vue';
import { storeToRefs } from 'pinia';
import { useUiStore } from '../../stores/uiStore';
import { getTypeLegend } from '../../lib/visualization/color-scheme';

export default {
  name: 'CategoryFilter',

  setup() {
    const uiStore = useUiStore();
    const { xray } = storeToRefs(uiStore);

    const typeLegend = getTypeLegend();
    const selectedCategories = computed(() => xray.value.categories || new Set());

    const isActive = (type) => {
      return selectedCategories.value.size === 0 || selectedCategories.value.has(type);
    };

    const allSelected = computed(() => {
      return selectedCategories.value.size === 0 || selectedCategories.value.size === typeLegend.length;
    });

    const toggleCategory = (type) => {
      const newCategories = new Set(selectedCategories.value);
      if (newCategories.has(type)) {
        newCategories.delete(type);
      } else {
        newCategories.add(type);
      }
      uiStore.setXRayCategories(newCategories);
    };

    const handleToggleAll = () => {
      if (allSelected.value) {
        // Clear all
        uiStore.setXRayCategories(new Set());
      } else {
        // Select all
        const allTypes = new Set(typeLegend.map(entry => entry.type));
        uiStore.setXRayCategories(allTypes);
      }
    };

    return {
      typeLegend,
      selectedCategories,
      allSelected,
      isActive,
      toggleCategory,
      handleToggleAll
    };
  }
};
</script>

// src/components/xray/CategoryFilter.tsx
/**
 * Category Filter Component
 *
 * Allows users to filter treemap by content type categories
 */

import { useAnalysisStore } from '../../store/analysis-store';
import { getTypeLegend } from '../../lib/visualization/color-scheme';

export function CategoryFilter() {
  const { xrayCategories, toggleXRayCategory } = useAnalysisStore();
  const typeLegend = getTypeLegend();

  // DEBUG: Log category state on every render
  console.log('[CategoryFilter] Current categories:', Array.from(xrayCategories), 'Size:', xrayCategories.size);

  const handleToggleAll = () => {
    // If all selected, clear all. Otherwise, select all.
    if (xrayCategories.size === typeLegend.length) {
      // Clear all
      typeLegend.forEach((entry) => {
        if (xrayCategories.has(entry.type)) {
          toggleXRayCategory(entry.type);
        }
      });
    } else {
      // Select all
      typeLegend.forEach((entry) => {
        if (!xrayCategories.has(entry.type)) {
          toggleXRayCategory(entry.type);
        }
      });
    }
  };

  const allSelected = xrayCategories.size === 0 || xrayCategories.size === typeLegend.length;

  return (
    <div>
      <div className="flex items-center justify-between mb-3">
        <h3 className="text-sm font-medium text-gray-900">Filter by Content Type</h3>
        <button
          onClick={handleToggleAll}
          className="text-sm text-blue-600 hover:text-blue-800 font-medium"
        >
          {allSelected ? 'Clear All' : 'Select All'}
        </button>
      </div>

      <div className="flex flex-wrap gap-2">
        {typeLegend.map((entry) => {
          const isActive = xrayCategories.size === 0 || xrayCategories.has(entry.type);

          return (
            <button
              key={entry.type}
              onClick={() => {
                console.log('[CategoryFilter] Before toggle:', entry.type, 'Categories:', Array.from(xrayCategories));
                toggleXRayCategory(entry.type);
                // Log after will happen in next render
              }}
              className={`inline-flex items-center gap-2 px-3 py-1.5 rounded-md text-sm font-medium transition-all ${
                isActive
                  ? 'bg-white border-2 border-gray-300 text-gray-900'
                  : 'bg-gray-100 border-2 border-transparent text-gray-400'
              }`}
            >
              <span
                className="w-3 h-3 rounded-sm"
                style={{ backgroundColor: entry.color }}
              />
              <span>{entry.label}</span>
            </button>
          );
        })}
      </div>

      {xrayCategories.size > 0 && xrayCategories.size < typeLegend.length && (
        <div className="mt-3 text-sm text-gray-600">
          Showing {xrayCategories.size} of {typeLegend.length} categories
        </div>
      )}
    </div>
  );
}
