// src/components/insights/InsightsView.vue
<!--
  Insights View Container
  Main container for the insights/recommendations view
-->
<template>
  <div v-if="!currentAnalysis" class="flex items-center justify-center h-full">
    <div class="text-gray-500">No analysis data available</div>
  </div>

  <div v-else-if="isAnalyzing" class="flex flex-col items-center justify-center h-full gap-4">
    <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600" />
    <div class="text-gray-700 font-medium">Analyzing for optimization opportunities...</div>
  </div>

  <div v-else-if="error" class="flex items-center justify-center h-full">
    <div class="bg-red-50 border border-red-200 rounded-lg p-6 max-w-lg">
      <h3 class="text-lg font-semibold text-red-900 mb-2">Analysis Error</h3>
      <p class="text-sm text-red-700">{{ error }}</p>
    </div>
  </div>

  <div v-else class="flex flex-col min-h-screen bg-white">
    <!-- Header -->
    <div class="p-4 border-b border-gray-200">
      <div class="flex items-center justify-between mb-4">
        <div>
          <h2 class="text-2xl font-bold text-gray-900">Optimization Insights</h2>
          <p class="text-sm text-gray-600">
            Automated recommendations to reduce app size
          </p>
        </div>

        <!-- Summary Stats -->
        <div
          v-if="filteredInsights.length > 0"
          class="bg-gradient-to-r from-blue-50 to-purple-50 border border-blue-200 rounded-lg p-4"
        >
          <div class="text-sm text-gray-600">Total Potential Savings</div>
          <div class="text-3xl font-bold text-blue-900">{{ formatBytes(totalSavings) }}</div>
          <div class="text-sm text-gray-600 mt-1">
            {{ totalSavingsPercent.toFixed(2) }}% of total size
          </div>
        </div>
      </div>

      <!-- Filters -->
      <InsightFilters
        :selected-severities="severityFilter"
        :selected-categories="categoryFilter"
        :group-by-severity="groupBySeverity"
        @severity-toggle="handleSeverityToggle"
        @category-toggle="handleCategoryToggle"
        @toggle-group-by-severity="groupBySeverity = !groupBySeverity"
      />
    </div>

    <!-- Insights List -->
    <div class="flex-1 p-4 overflow-auto">
      <div v-if="filteredInsights.length === 0" class="flex items-center justify-center py-12">
        <div class="text-center">
          <div class="text-4xl mb-4">✨</div>
          <h3 class="text-lg font-semibold text-gray-900 mb-2">No insights to display</h3>
          <p class="text-sm text-gray-600">
            {{ insights.length === 0
              ? 'Great job! Your app is well optimized.'
              : 'Try adjusting the filters to see more insights.'
            }}
          </p>
        </div>
      </div>

      <!-- Grouped by Severity -->
      <div v-else-if="groupBySeverity">
        <SeveritySection
          v-for="severity in ['critical', 'high', 'medium', 'low']"
          :key="severity"
          :severity="severity"
          :insights="groupedInsights[severity] || []"
        />
      </div>

      <!-- Flat List -->
      <div v-else class="space-y-4">
        <InsightCard
          v-for="(insight, index) in filteredInsights"
          :key="`${insight.ruleId}-${index}`"
          :insight="insight"
        />
      </div>
    </div>
  </div>
</template>

<script>
import { ref, computed, watch, onMounted } from 'vue';
import { storeToRefs } from 'pinia';
import { useAnalysisStore } from '../../stores/analysisStore';
import InsightCard from './InsightCard.vue';
import InsightFilters from './InsightFilters.vue';
import SeveritySection from './SeveritySection.vue';
import { getDefaultInsightEngine } from '../../lib/analysis';
import { formatBytes } from '../../utils/formatters';

export default {
  name: 'InsightsView',

  components: {
    InsightCard,
    InsightFilters,
    SeveritySection
  },

  setup() {
    const analysisStore = useAnalysisStore();
    const { currentAnalysis } = storeToRefs(analysisStore);

    const isAnalyzing = ref(false);
    const error = ref(null);
    const insights = ref([]);
    const severityFilter = ref(new Set());
    const categoryFilter = ref(new Set());
    const groupBySeverity = ref(true);

    // Run insights analysis when view loads
    const runAnalysis = async () => {
      if (!currentAnalysis.value || insights.value.length > 0) return;

      isAnalyzing.value = true;
      error.value = null;

      try {
        const engine = getDefaultInsightEngine();
        const results = await engine.executeAll(currentAnalysis.value);
        insights.value = results;
      } catch (err) {
        console.error('[InsightsView] Analysis failed:', err);
        error.value = err instanceof Error ? err.message : 'Unknown error occurred';
      } finally {
        isAnalyzing.value = false;
      }
    };

    onMounted(() => {
      runAnalysis();
    });

    watch(currentAnalysis, () => {
      if (currentAnalysis.value) {
        insights.value = [];
        runAnalysis();
      }
    });

    // Filter insights
    const filteredInsights = computed(() => {
      let filtered = insights.value;

      if (severityFilter.value.size > 0) {
        filtered = filtered.filter((insight) =>
          severityFilter.value.has(insight.severity)
        );
      }

      if (categoryFilter.value.size > 0) {
        filtered = filtered.filter((insight) =>
          categoryFilter.value.has(insight.category)
        );
      }

      return filtered;
    });

    // Group insights by severity
    const groupedInsights = computed(() => {
      if (!groupBySeverity.value) return null;

      const groups = {
        critical: [],
        high: [],
        medium: [],
        low: []
      };

      filteredInsights.value.forEach((insight) => {
        groups[insight.severity].push(insight);
      });

      // Sort within each group by potentialSavings
      Object.values(groups).forEach((group) => {
        group.sort((a, b) => (b.potentialSavings || 0) - (a.potentialSavings || 0));
      });

      return groups;
    });

    // Calculate total savings
    const totalSavings = computed(() => {
      return filteredInsights.value.reduce((sum, insight) => sum + (insight.potentialSavings || 0), 0);
    });

    const totalSavingsPercent = computed(() => {
      if (!currentAnalysis.value) return 0;
      return (totalSavings.value / currentAnalysis.value.totalInstallSize) * 100;
    });

    // Handle filter toggles
    const handleSeverityToggle = (severity) => {
      const newFilter = new Set(severityFilter.value);
      if (newFilter.has(severity)) {
        newFilter.delete(severity);
      } else {
        newFilter.add(severity);
      }
      severityFilter.value = newFilter;
    };

    const handleCategoryToggle = (category) => {
      const newFilter = new Set(categoryFilter.value);
      if (newFilter.has(category)) {
        newFilter.delete(category);
      } else {
        newFilter.add(category);
      }
      categoryFilter.value = newFilter;
    };

    return {
      currentAnalysis,
      isAnalyzing,
      error,
      insights,
      severityFilter,
      categoryFilter,
      groupBySeverity,
      filteredInsights,
      groupedInsights,
      totalSavings,
      totalSavingsPercent,
      handleSeverityToggle,
      handleCategoryToggle,
      formatBytes
    };
  }
};
</script>

// src/components/insights/InsightsView.tsx
/**
 * Insights View Container
 *
 * Main container for the insights/recommendations view
 */

import { useState, useEffect, useMemo } from 'react';
import { useAnalysisStore } from '../../store/analysis-store';
import { InsightCard } from './InsightCard';
import { InsightFilters } from './InsightFilters';
import { SeveritySection } from './SeveritySection';
import { getDefaultInsightEngine } from '../../lib/analysis';
import { formatBytes } from '../../utils/formatters';
import type { InsightCategory, InsightSeverity, InsightResult } from '../../types/insights';

export function InsightsView() {
  const {
    currentAnalysis,
    insights,
    insightsSeverityFilter,
    insightsCategoryFilter,
    insightsGroupBySeverity,
    setInsights,
    setInsightsSeverityFilter,
    setInsightsCategoryFilter,
    setInsightsGroupBySeverity,
  } = useAnalysisStore();

  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Run insights analysis when view loads
  useEffect(() => {
    if (!currentAnalysis) return;

    // Check if insights are already computed
    if (insights.length > 0) {
      console.log('[InsightsView] Using cached insights');
      return;
    }

    // Run insights analysis
    const runAnalysis = async () => {
      setIsAnalyzing(true);
      setError(null);

      try {
        console.log('[InsightsView] Running insights analysis...');
        const engine = getDefaultInsightEngine();
        const results = await engine.executeAll(currentAnalysis);

        console.log(`[InsightsView] Found ${results.length} insights`);
        setInsights(results);
      } catch (err) {
        console.error('[InsightsView] Analysis failed:', err);
        setError(err instanceof Error ? err.message : 'Unknown error occurred');
      } finally {
        setIsAnalyzing(false);
      }
    };

    runAnalysis();
  }, [currentAnalysis, insights.length, setInsights]);

  // Filter insights based on selected filters
  const filteredInsights = useMemo(() => {
    let filtered = insights;

    // Filter by severity
    if (insightsSeverityFilter.size > 0) {
      filtered = filtered.filter((insight) =>
        insightsSeverityFilter.has(insight.severity)
      );
    }

    // Filter by category
    if (insightsCategoryFilter.size > 0) {
      filtered = filtered.filter((insight) =>
        insightsCategoryFilter.has(insight.category)
      );
    }

    return filtered;
  }, [insights, insightsSeverityFilter, insightsCategoryFilter]);

  // Group insights by severity when enabled
  const groupedInsights = useMemo(() => {
    if (!insightsGroupBySeverity) {
      return null; // Flat list mode
    }

    const groups: Record<InsightSeverity, InsightResult[]> = {
      critical: [],
      high: [],
      medium: [],
      low: [],
    };

    filteredInsights.forEach((insight) => {
      groups[insight.severity].push(insight);
    });

    // Sort within each group by potentialSavings (descending)
    Object.values(groups).forEach((group) => {
      group.sort((a, b) => b.potentialSavings - a.potentialSavings);
    });

    return groups;
  }, [filteredInsights, insightsGroupBySeverity]);

  // Calculate total potential savings
  const totalSavings = useMemo(() => {
    return filteredInsights.reduce((sum, insight) => sum + insight.potentialSavings, 0);
  }, [filteredInsights]);

  const totalSavingsPercent = useMemo(() => {
    if (!currentAnalysis) return 0;
    return (totalSavings / currentAnalysis.totalInstallSize) * 100;
  }, [totalSavings, currentAnalysis]);

  // Handle filter toggles
  const handleSeverityToggle = (severity: InsightSeverity) => {
    const newFilter = new Set(insightsSeverityFilter);
    if (newFilter.has(severity)) {
      newFilter.delete(severity);
    } else {
      newFilter.add(severity);
    }
    setInsightsSeverityFilter(newFilter);
  };

  const handleCategoryToggle = (category: InsightCategory) => {
    const newFilter = new Set(insightsCategoryFilter);
    if (newFilter.has(category)) {
      newFilter.delete(category);
    } else {
      newFilter.add(category);
    }
    setInsightsCategoryFilter(newFilter);
  };

  // Loading state
  if (!currentAnalysis) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-gray-500">No analysis data available</div>
      </div>
    );
  }

  if (isAnalyzing) {
    return (
      <div className="flex flex-col items-center justify-center h-full gap-4">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600" />
        <div className="text-gray-700 font-medium">Analyzing for optimization opportunities...</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="bg-red-50 border border-red-200 rounded-lg p-6 max-w-lg">
          <h3 className="text-lg font-semibold text-red-900 mb-2">Analysis Error</h3>
          <p className="text-sm text-red-700">{error}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col min-h-screen bg-white">
      {/* Header */}
      <div className="p-4 border-b border-gray-200">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h2 className="text-2xl font-bold text-gray-900">Optimization Insights</h2>
            <p className="text-sm text-gray-600">
              Automated recommendations to reduce app size
            </p>
          </div>

          {/* Summary Stats */}
          {filteredInsights.length > 0 && (
            <div className="bg-gradient-to-r from-blue-50 to-purple-50 border border-blue-200 rounded-lg p-4">
              <div className="text-sm text-gray-600">Total Potential Savings</div>
              <div className="text-3xl font-bold text-blue-900">{formatBytes(totalSavings)}</div>
              <div className="text-sm text-gray-600 mt-1">
                {totalSavingsPercent.toFixed(2)}% of total size
              </div>
            </div>
          )}
        </div>

        {/* Filters */}
        <InsightFilters
          selectedSeverities={insightsSeverityFilter}
          selectedCategories={insightsCategoryFilter}
          onSeverityToggle={handleSeverityToggle}
          onCategoryToggle={handleCategoryToggle}
          groupBySeverity={insightsGroupBySeverity}
          onGroupBySeverityToggle={() => setInsightsGroupBySeverity(!insightsGroupBySeverity)}
        />
      </div>

      {/* Insights List - With max-width for readability and responsive padding */}
      <div className="max-w-4xl mx-auto px-4 md:px-6 lg:px-8 py-4">
        {filteredInsights.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-12 text-center">
            {insights.length === 0 ? (
              <>
                <div className="text-6xl mb-4">🎉</div>
                <h3 className="text-xl font-semibold text-gray-900 mb-2">
                  No Optimization Opportunities Found
                </h3>
                <p className="text-sm text-gray-600 max-w-md">
                  Your app is already well-optimized! No major issues detected by our analysis rules.
                </p>
              </>
            ) : (
              <>
                <div className="text-6xl mb-4">🔍</div>
                <h3 className="text-xl font-semibold text-gray-900 mb-2">
                  No Insights Match Your Filters
                </h3>
                <p className="text-sm text-gray-600 max-w-md">
                  Try adjusting your severity or category filters to see more insights.
                </p>
              </>
            )}
          </div>
        ) : groupedInsights ? (
          // Grouped view
          <div>
            {groupedInsights.critical.length > 0 && (
              <SeveritySection severity="critical" insights={groupedInsights.critical} />
            )}
            {groupedInsights.high.length > 0 && (
              <SeveritySection severity="high" insights={groupedInsights.high} />
            )}
            {groupedInsights.medium.length > 0 && (
              <SeveritySection severity="medium" insights={groupedInsights.medium} />
            )}
            {groupedInsights.low.length > 0 && (
              <SeveritySection severity="low" insights={groupedInsights.low} />
            )}
          </div>
        ) : (
          // Flat list view
          <div className="space-y-4">
            {filteredInsights.map((insight, index) => (
              <InsightCard key={`${insight.ruleId}-${index}`} insight={insight} />
            ))}
          </div>
        )}
      </div>

      {/* Footer */}
      {filteredInsights.length > 0 && (
        <div className="p-4 border-t border-gray-200 bg-gray-50">
          <div className="flex items-center justify-between text-sm">
            <div className="text-gray-600">
              Showing {filteredInsights.length} of {insights.length} insights
            </div>
            <div className="text-gray-600">
              {filteredInsights.filter((i) => i.severity === 'critical').length} critical ·{' '}
              {filteredInsights.filter((i) => i.severity === 'high').length} high ·{' '}
              {filteredInsights.filter((i) => i.severity === 'medium').length} medium ·{' '}
              {filteredInsights.filter((i) => i.severity === 'low').length} low
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
